#!/usr/bin/env bash
python train.py --ymlpath=experiment/singleview2500/d2_singleview2500.yml --gpu=0 --dataroot=./data/LIDC-HDF5-256 --dataset=train --tag=d2_singleview2500_lidc --data=data/chengsq/AECT-GAN/model_dic/Sig_AECT-GAN --dataset_class=align_ct_xray_std --model_class=SingleView-AECT-GAN --datasetfile=./data/train.txt --valid_datasetfile=./data/test.txt --valid_dataset=test

python train.py --ymlpath=experiment/multiview2500/d2_multiview2500.yml --gpu=0 --dataroot=./data/LIDC-HDF5-256 --dataset=train --tag=d2_multiview2500_lidc --data=data/chengsq/AECT-GAN/model_dic/MultiView-AECT-GAN --dataset_class=align_ct_xray_views_std --model_class=MultiView-AECT-GAN --datasetfile=./data/train.txt --valid_datasetfile=./data/test.txt --valid_dataset=test

python train.py --ymlpath=experiment/singleview2500/d2_singleview2500.yml --gpu=0 --dataroot=./data/GAN-dataset-complete-new-unnorm --dataset=train --tag=d2_singleview2500_synthetic --data=data/chengsq/AECT-GAN/model_dic/Sig_AECT-GAN --dataset_class=align_ct_xray_std --model_class=SingleView-AECT-GAN --datasetfile=./data/synthetic_train.txt --valid_datasetfile=./data/synthetic_test.txt --valid_dataset=test

python train.py --ymlpath=experiment/multiview2500/d2_multiview2500.yml --gpu=0 --dataroot=./data/GAN-dataset-complete-new-unnorm --dataset=train --tag=d2_multiview2500_synthetic --data=data/chengsq/AECT-GAN/model_dic/MultiView-AECT-GAN --dataset_class=align_ct_xray_views_std --model_class=MultiView-AECT-GAN --datasetfile=./data/synthetic_train.txt --valid_datasetfile=./data/synthetic_test.txt --valid_dataset=test

python train.py --ymlpath=experiment/singleview2500/d2_singleview2500.yml --gpu=0 --dataroot=./data/GAN-dataset-complete-new-real-unnorm --dataset=train --tag=d2_singleview2500_real --data=data/chengsq/AECT-GAN/model_dic/Sig_AECT-GAN --dataset_class=align_ct_xray_std --model_class=SingleView-AECT-GAN --datasetfile=./data/real_train.txt --valid_datasetfile=./data/real_test.txt --valid_dataset=test

python train.py --ymlpath=experiment/multiview2500/d2_multiview2500.yml --gpu=0 --dataroot=./data/GAN-dataset-complete-new-real-unnorm --dataset=train --tag=d2_multiview2500_real --data=data/chengsq/AECT-GAN/model_dic/MultiView-AECT-GAN --dataset_class=align_ct_xray_views_std --model_class=MultiView-AECT-GAN --datasetfile=./data/real_train.txt --valid_datasetfile=./data/real_test.txt --valid_dataset=test
